name: stevenn
favicon: null
layout_spectrum: 0.8355059027671814
typography_spectrum: 0.09108267538249493
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5325362503062934
  lightness: 0.9778571405913681
  saturation: 0.2962476913817227
  rhythmicContrast: 0.3589312091935426
purpose: []
