name: stevenn
favicon: null
layout_spectrum: 0.79868
typography_spectrum: 0.91734
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dce9f2'
    - '#0f1012'
    - '#544c49'
    - '#a5b6bf'
    - '#766e6b'
  brandStrength: 0.5325362503062934
  lightness: 0.75
  saturation: 0.2962476913817227
  rhythmicContrast: 0.3589312091935426
purpose: []
